# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: svdb.co
subtitle: Rants and musings
description: My name is Sjaak van den Berg and I'm a developer working with blockchain technology. You can reach me on Twitter via <a href='https://twitter.com/svdb'>@svdb</a>.
author: Sjaak van den Berg
email: mail@svdb.co
twitter: svdb
language: en
timezone: Europe/Amsterdam

# Disqus
disqus_shortname: svdbco

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://svdb.co
root: /
permalink: posts/:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: '*.md'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: true
relative_link: false
future: false
highlight:
  enable: true
  line_number: true
  tab_replace: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: dddd MMMM Do YYYY
time_format: H:mm ZZ

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: svdb
exclude_generator: ['archive', 'tag', 'category']

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki/
markdown:
  render:
    html: true # escape HTML content
    xhtmlOut: false # produce fully XHTML compliant code
    breaks: false # don't produce `<br>` on line break
    linkify: true # returns text links as HTML links
    typographer: true # substitute common elements like (c)
  anchors:
    level: 2
    permalink: false
  plugins:
    - markdown-it-footnote
    - markdown-it-sup
    - markdown-it-sub

# Stylus
## https://github.com/hexojs/hexo-renderer-stylus
stylus:
  compress: false
  sourcemaps:
    comment: true
    inline: true
    sourceRoot: ''
    basePath: .

# Autoprefixer
## https://github.com/hexojs/hexo-autoprefixer
autoprefixer:
  enable: true
  debug: true
  cascade: false
  browsers:
    - '> 5%'
    - 'last 2 versions'
  safe: false
  exclude:
  - '*.min.js'

# CleanCSS
## https://github.com/hexojs/hexo-clean-css
clean_css:
  compatibility: true
  exclude:
    - '*.min.css'
  processImport: true

# HTMLMinifier
## https://github.com/hexojs/hexo-html-minifier
# html_minifier:
#   collapseWhitespace: true
#   exclude:
#   removeComments: true
#   useShortDoctype: true
#   minifyJS: true

# Uglify
## https://github.com/hexojs/hexo-uglify
uglify:
  mangle: true # single letter vars
  output:
  compress:
  comments: # `all` to keep
  exclude:
    - '*.min.js'

# RSS Feed
## https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: /atom.xml
  limit: 50

# Sitemap
## https://github.com/hexojs/hexo-generator-sitemap
sitemap:
  path: /sitemap.xml

# Server
## https://github.com/hexojs/hexo-server
server:
  port: 4000
  log: false
  ip: 0.0.0.0

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:sjaakvandenberg/sjaakvandenberg.github.io.git
  branch: master
