# config
# logo: //blog.ghost.org/content/images/2013/Nov/bloglogo_1-1.png
# cover: http://oi58.tinypic.com/14xjbxu.jpg
logo: /images/svdb.png
keywords: "sjaak van den berg, svdb, bitcoin, crypto, payment, integration, bitcoins, wordpress, betaling, webshop, front end, design, ontwerp, developer"
pubkey: 13DB CAA1 2633 81A7

# Content
excerpt_link: Read more

# Miscellaneous
rss: /atom.xml
google_analyticz: UA-51823806-1
